export const skillIcons = {
  'javascript': 'simple-icons:javascript',
  'typescript': 'devicon-plain:typescript',
  'vue.js': 'simple-icons:vuedotjs',
  'vuetify': 'simple-icons:vuetify',
  'nuxt': 'simple-icons:nuxt',
  'html': 'simple-icons:html5',
  'css': 'simple-icons:css3',
  'tailwind css': 'simple-icons:tailwindcss',
  'java': 'nonicons:java-16',
  'c#': 'nonicons:c-sharp-16',
  '.net': 'devicon-plain:dot-net',
  'ef core': 'devicon-plain:entityframeworkcore',
  'restful api': 'carbon:api',
  'postgresql': 'simple-icons:postgresql',
  'docker': 'simple-icons:docker',
  'kubernetes': 'simple-icons:kubernetes',
  'aws': 'simple-icons:amazonaws',
  'git': 'simple-icons:git',
  'github': 'simple-icons:github',
  'gitlab': 'simple-icons:gitlab',
  'sqlite': 'simple-icons:sqlite',
  'sql server': 'devicon-plain:microsoftsqlserver',
  'golang': 'simple-icons:go',
  'bash': 'simple-icons:gnubash',
  'linux': 'simple-icons:linux',
  'proxmox': 'simple-icons:proxmox',
  'opnsense': 'simple-icons:opnsense',
  'networking': 'carbon:network-4',
  'security': 'carbon:security',
  'virtualization': 'carbon:virtual-machine',
  'backup strategy': 'carbon:ibm-cloud-backup-service-vpc',
  'python': 'simple-icons:python',
  'fastapi': 'devicon-plain:fastapi',
}

export const socialIcons = {
  github: 'simple-icons:github',
  linkedin: 'simple-icons:linkedin',
  x: 'simple-icons:x',
  gitlab: 'simple-icons:gitlab',
}
